### ISSUE TITLE
Variablen Editor: Design > Themes > Bearbeiten

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#1014]
Im Moment kann nur Sven Variablen (die config.scss) anpassen und somit das Design einer Installation verändern. Zukünftig soll das auch für das wirHub-Core-Team möglich sein. Hierfür brauchen wir einen Variablen Editor. 

- Variablen können gesucht werden
- Variablen sollten mindestens in Figma in der wirHub UI Library dokumentiert sein
- Aktueller Wert der Variable wird angezeigt
- Variablen-Wert kann durch neuen Wert ersetzt werden > geändert (2 Spalten)
- Nach Speichern ("Compilen") Sucess- oder Fehler-Meldung via Snackbar

**Design:**
https://www.figma.com/design/hmz3cNKTYTdrNQAwQBk1b3/Features?node-id=2135-1714&t=ggfutEC91yXLvvEh-1

**ToDo's:**
Modal unter "Design/Themes/Bearbeiten" anpassen/erweitern
- [x] Statt Modal Overlay einsetzen?
- [x] Input für Name aus aktuellem Modal
- [x] Schriftarten aus aktuellem Modal, aber Checkboxen max. 3 untereinander und dann nebeneinander in Spalten bei mehreren Schriften
- [x] Variablen Headline
- [x] ~~Filterung via Tags und Suchfeld (Suche mit Keys)~~
- [x] "!default" automatisch rausfiltern in der Ausgabe
- [x] Komplette Variablen-Liste mit disabled "Default"- und "Neuer Wert" Spalte
- [x] Pagination einsetzen, max. 20 pro Seite
- [x] Nach Speichern ("Compilen") Sucess- oder Fehler-Meldung via Snackbar

**Comment by pmdevelopment** [comment]
Fortsetzung: https://github.com/wirDesign-communication-AG/wirhub-app/issues/1059
