### ISSUE TITLE
SmartTool Mediacockpit: Upload-Funktion

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#453]
**ToDos**
- [x] Verortet unter Tools > Media Upload
- [x] Funktionsweise ähnlich zu Filetransfer
- [x] Schreibrechte in bestimmte Ordner/Unterordnerstruktur in Mediacockpit
- [x] Nutzer kann via Dropdown entscheiden in welchen Unterordner (welche Abteilung) das Asset geladen werden soll
- [x] Nach Upload erhält Nutzer nur eine Bestätigung über erfolgreichen Upload (keine History, keine weiteren Schritte notwendig)

**Erste Schätzung Aufwand**
20h 

**Briefing Upload-Funktion:**
Bzgl. der angedachten Upload-(bzw. Contribute-)Funktion haben wir nach einer pragmatischen Lösung gesucht, über die eine Agentur uns (finale) Medien-Assets ins Mediacockpit hochladen kann. Diese sollen einfach in einem zentralen MAM-Ordner ankommen, von wo sie geprüft, mit Attributen angereichert und anschließend in die MAM-Struktur einsortiert werden.

Erster Gedanke war, dass wir Agenturen einen stark abgespeckten Zugang fürs Mediacockpit geben, wo ihnen lediglich ein Upload-Ordner zur Verfügung steht. Allerdings ist das Mediacockpit-Backend als auch die dortige Upload-Funktion nicht sehr intuitiv. Deswegen dachten wir, dass wir eine einfache Upload-Maske im BrandHub einbinden könnten, über die das möglich wäre (wir haben gesehen, dass bei KWS etwas ähnliches existiert). 

Angedachter Use Case: 1. Agentur wählt aus, für welche FUCHS-Gesellschaft die Dateien hochgeladen werden / 2. Dateien werden in den Upload-Ordner gezogen (Hinweis: Bei Videos oder offenen Print-Daten können es auch schon mal mehr als 1GB sein) / 3. Datei(en) werden in den entsprechenden Ordner ins Media-Cockpit übertragen.
