### ISSUE TITLE
v3.0.0

### ISSUE THREAD

**Issue by pmdevelopment** [wirDesign-communication-AG/wirhub-app#497]
## Voraussichtlicher Release
17.04.

## Beschreibung
Ziel der v3.0 ist eine verbesserte Projektstruktur für ein ideales Container-Setup:

- Es gibt ein Docker-Repository, das die Docker-Konfiguration enthält
- Es gibt ein generisches wirHub Projekt-Repository
    - Enthält ein Symfony Flex Projekt
    - Enhtält den Basis-Workflow für GitHub Actions zum Functional Testing
    - Lädt per Composer  die wirHub Applikation in der aktuellsten Version
    - Per Workflow (oder Composer?) wird das Docker-Repository ins Projekt gecloned
    - Das Tagging eines Commits löst den Deployment Prozess aus

- Kunden mit individuellem Code/Deployment erhalten ein Fork des generischen Projekt-Repositories. Individuelle Bestandteile werden Teil des Kunden-Repositories.

## ToDos
- [x] StyleBundle auflösen
- [x] AppBundle wird zu "WirhubBundle"
- [x] Neues Repository mit einem Symfony Flex Projekt
- [x] "WirhubBundle" übernimmt die Konfiguration des Flex-Projekts
- [x] Verschiebung der Themes in den "files/" Ordner, damit nur 1 Pfad auserhalb des Image bestehen muss
- [x] Weiterleitung auf die LastVisitedUrl nach Login
- [x] AccessTokenLogoutSuccessHandler in EventSubscriber überführen
- [x] SmartBlock Accordion: Öffnet nicht nach hinzufügen
- [x] Update guide
