### ISSUE TITLE
SmartTool mediacockpit: Document Library

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#512]
**ToDos**
- [x] Die in mediacockpit gepflegten Varianten, stehen als Download zur Verfügung
- [x] Einstellungen für Ansicht einbauen ("List","Kachel","Beides")
- [x] Anzahl Suchergebnisse zeigen ("~")

**Budget**
3h
