### ISSUE TITLE
SmartBlock Attachement: Diverse Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#535]
**User Stories**
_Als Nutzer möchte ich alle in einem Attachement SmartBlock hinterlegten Downloads mit einem Klick herunterladen können, um Zeit zu sparen._ 

_Als Nutzer möchte ich mir bei Bedarf den vollen Dateinamen via Tooltip ansehen können, um zu entscheiden, ob es sich um die richtige Datei handelt, bevor ich sie herunterlade._

**ToDos Design**
- [x] UI Design für Funktion "Alle Dateien herunterladen"

**ToDos Entwicklung**
- [x] Tooltip mit kompletten Dateinamen on mouse-over
- [x] Download aller Dateien umsetzen
- [x] Show all umsetzen
- [x] Option für Collection-Download in Inline-Toolbar ergänzen

**Design**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=2372%3A29370&t=pOL0q1P6L2R1TlvG-1

**Budget** 
4h
