### ISSUE TITLE
Anbindung CELUM: Funktioniert nicht

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#547]
**ToDos**
- [x]  individueller Button-Text wird nicht angezeigt 
- [x]  im Media Creator wird Button gar nicht angezeigt 
- [x] Integration in Smart-Blocks öffnet 404
