### ISSUE TITLE
SmartBlock Bühne: Diverse Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#569]
**ToDos**
- [x] auf 2 Design-Varianten reduzieren: Bühne Allgemein, Bühne mit Most Visited (siehe Figma)
- [x] Variablen für background-text, background-most-visited, min-height (45-100vh)
- [x] Pfeil hinter Links in Brand-Color

**Design**
https://www.figma.com/file/4lvLk6rYqvKWJgf5hcjIsH/wirHub-Components-%26-Prototype?node-id=2412%3A29057&t=8A8MPPeVvzhoScQd-1
