### ISSUE TITLE
SmartTool Media Upload: Erweiterungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#617]
Briefing-Unterlagen siehe [hier](https://wirdesignde.sharepoint.com/:f:/r/sites/FUCHSBrandportal/Freigegebene%20Dokumente/General/Media%20Upload?csf=1&web=1&e=CgnFad).

**ToDos**
- [x] Kommentarfeld ergänzen in A_BH_Comment
- [x] Absender ergänzen in A_BH_Source = E-Mail Adresse des eingeloggten Nutzers
- [x] Division = Please choose receiving company

**Comment by pmdevelopment** [comment]
![Screenshot 2023-06-05 111429](https://github.com/wirDesign-communication-AG/wirhub-app/assets/4947485/36625d0c-8bbc-4c15-842d-43dcfab986e7)
