### ISSUE TITLE
SmartBlock Text: Inline-Edit Improvements

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#644]
**ToDos**
- [x] Bearbeiten direkt möglich (durch Klick in das Textfeld)
- [x] Neue Versionierung s.u.
- [x] Alte History ggf. entfernen
- [x] Toolbar-Design vom CKEditor anpassen

**Verhalten neue Versionierung** 
* Eine neue Version wird nur gespeichert  wenn Inhalt sich ändert, nicht wenn nur Styles sich ändern
* Eine neue Version wird gespeichert, sobald erstmalig neuer Inhalt übermittelt wird
