### ISSUE TITLE
Öffentlicher wirHub: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#698]
**ToDos**
- [x] Navigation: alle Unterpunkte anzeigen
- [x] Navigation: Schlüssel durch Schloss ersetzen und alle Icons rechtsbündig, siehe [Design](https://www.figma.com/file/hmz3cNKTYTdrNQAwQBk1b3/Features?type=design&node-id=208-14494&mode=design&t=162FYZ1XTxgrW8od-4)
- [x] Rekursive Vererbung, wenn ein Oberpunkt öffentlich gestellt wird auf Unterseiten und Inhalte der Seiten
- [x] Login-Dialog für nicht öffentliche Unterseiten
