### ISSUE TITLE
Einstellungen > Funktionen: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#737]
- [x] Funktionen: Ersten Reiter entfernen
- [x] Funktionen: Reihenfolge ändern in Rechtliches, Neuigkeiten, Formulare, Freigabe, Anbindungen
- [x] SmartBlocks unter Administration mit den Reitern "Farben" und "UI Pattern"
- [x] SmarTools unter Administration mit den Reitern "Inspiration""Framing Tool" und "File Transfer"
- [x] Frontend umbenennen in "Design". Administration > Einstellungen auflösen und  als "Global"-Reiter integrieren. Reihenfolge unter Design: Global, Login (=Anmelden), Frontend (=Themes)
- [x] E-Mail Signatur zu Sprachen packen
- [x] Reihenfolge: Design, Benutzer, Spaces, SmartBlocks, SmartTools, Funktionen, Sprachen, Analytics, System
- [x] Sprachen > Templates in "E-Mail Templates" umbenennen

### Subtasks UI-Pattern

- [x] appSettingsPatternIndex umziehen
- [x] PatternController final umziehen
- [x] "Style" Template überarbeiten
- [x] "Style" und "JavaScript" durchtesten
