### ISSUE TITLE
Downloadcenter: Diverse Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#757]
**ToDos** 
- [x] webp und potx zur Liste der automatischen Thumbnails hinzufügen (auch bei SB Anhang)
- [x] Tags in globaler Suche berücksichtigen
- [x] Design Tags anpassen (kein helles Orange)
- [x] Sortierung Default von alphabetisch zu Beliebtheit Absteigend ändern
