### ISSUE TITLE
SmartBlock Do/Don't: Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#818]
**ToDos**
- [x] Anpassung Design der Uploadfelder – Beachten: Verändertes Design in den Columns
- [x] Hinzufügen weiterer Items über Inline-Toolbar
- [x] Inline Text Edit
- [x] Prüfen ob Spalten verändert wurden
- [x] neue Text-Option: oben & unten
- [x] neue Stile
- [x] Überarbeitung der Item-Toolbar
- [x] Bilder hinzufügen/austauschen öffnet direkt Datei explorer
- [x] Sonderfall Spalten: Veränderte Umbrüche abhängig von Spaltenanzahl im Spaltenblock (Columns)
- [x] Verschieben per Drag and Drop über das gesamte Item
- [x] Alternative Dialoge für DAM integrieren

**Design**
https://www.figma.com/file/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?type=design&node-id=1347-2014&mode=design&t=JRZCidB22ndXCgtj-4
