### ISSUE TITLE
SmartBlock Kapitel Teaser: Inline-Edit finalisieren

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#824]
**Design:**
https://www.figma.com/design/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?node-id=2854-6421&t=pfiI5s8i2fwFSfYL-1

--

**ToDo's:**
- [x] Edit-Button aus Toolbar entfernen

Bearbeiten hier in Modal lassen
- [ ] MDE durch CKEditor ersetzen
- [ ] neue Funktion: Links in neuem Tab öffnen als Checkbox unter URL-Inputfeld und Kategorie-Dropdown
- [ ] Auwahl der Seiten einschränken, auf die Seiten, die der Nutzer bearbeiten darf
- [ ] Styles checken analog neuem Design (bspw. Textbutton bitte aktualisieren analog neuen Button-Styles)
- [ ] Reihenfolge der Cards durch Drag&Drop wie bei Farben

**Weitere Bugs, die optimiert werden sollten:**
- [ ] https://github.com/wirDesign-communication-AG/wirhub-app/issues/999
- [ ] https://github.com/wirDesign-communication-AG/wirhub-app/issues/1000
