### ISSUE TITLE
SmartTool Icon Library: Diverse Optimierungen

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#841]
**ToDos**
- [x] Abstand zwischen Download-Button und Placeholder (2xl)
- [x] Möglichkeit einfarbige Platzhalter hochzuladen
- [x] ~~Wird ein einfarbige Farbvariante gewählt, werden alle Pfade eines mehrfarbigen Icons in diese Farbe eingefärbt – es wird also zu einem einfarbigen Icon~~
- [x] Top Tags in der Tag-Suche direkt auflisten
- [x] Filter zurücksetzen (analog Fuchs: "Reset filters", Sven weiß Bescheid)

**Nice to have**
- [x] Anzahl der Icons ergänzen (KS liefert Design)

Nice to have wird in #848 fortgesetzt.

**Comment by Kschneider94** [comment]
@ChristinaGu 

Kannst du oben bitte noch das ToDo ergänzen? Ich kann es leider nicht editieren:

- Filter zurücksetzen (analog Fuchs: "Reset filters", Sven weiß Bescheid)
