### ISSUE TITLE
SmartTool Icon Library: Diverse Optimierungen 2.0

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#867]
**ToDo's Editor:**
- [x] Beschreibung in "Schlagwörter" umbenennen
- [x] Tags in "Collections" umbenennen
- [x] Neuer Tab für "Collections" als Übersicht --> Liste mit allen Collections (Tags), um sie dort umbenennen, löschen oder Neue hinzufügen zu können
- [x] Klick auf Inputfeld in der Collections-Spalte: Flyout mit allen Tags anzeigen lassen (Max-height: ca. 8 Tags); neue Collections können dort wie aktuell auch weiterhin hinzugefügt werden
 
**ToDo's Frontend:**
- [x] Suchfeld muss alles filtern: Dateiname, Schlagwörter und Collections (Tags)
(Beispiel bei VKB: sie haben "Hände" als Collection angelegt. Wenn man Hände in die Suche eingibt, werden genau diese Icons nicht angezeigt. Nur die Icons, die als Schlagwörter Hände zugeteilt bekommen haben. Die meisten werden nur die Suche nutzen, um schnell ein Icon zu finden)
- [x] Collections:
Wenn in den Einstellungen keine Collections hinterlegt sind, dann im Frontend ausblenden
Mit Klick auf Dropdown/Suchfeld öffnet sich das Flyout mit allen Collections (analog Editor)
- [x] Secondary Button "Alle Ergebnisse auswählen" ergänzen --> Alle Icons, die angezeigt werden, werden ausgewählt
- [x] Sidebar: "Meine Auswahl" ab 6 Icons automatisch zuklappen
