### ISSUE TITLE
Spaces: Ein- und Ausblenden

### ISSUE THREAD

**Issue by ChristinaGu** [wirDesign-communication-AG/wirhub-app#877]
**User Storie:**
Als Administrator möchte ich Spaces aus- und einblenden können

**ToDos**
Hinweise Frontend:
Ausgeblendete Spaces müssen in der Sidebar/Space-Switch/Breacrumb ausgeblendet werden: 
- [x] --> Admins/Editor: Spacename mit Icon (visibility_off) 
- [x] --> User: komplett ausgeblendet
Ausgeblendete Spaces müssen im Spaces-Modul auf der Startseite ausgeblendet werden: 
- [x] Cards: --> Admins/Editor: Card mit Icon (visibility_off) --> User: komplett ausgeblendet 
- [x] ~~Modal: --> Admins/Editor: Spacename mit Icon (visibility_off)~~

Hinweise Backend:
- [x] Unter “Spaces” müssen Spaces ein- und ausgeblendet werden können; Funktion analog Seiten? ---> “Seiten einblenden”/”Seite ausblenden”

**Design**
https://www.figma.com/file/hmz3cNKTYTdrNQAwQBk1b3/Features?type=design&node-id=1272%3A3&mode=design&t=b91ysHam8iYn9bW2-1

**Comment by pmdevelopment** [comment]
Im SmartBlock Spaces entfällt das Icon in der Auswahl der Spaces aufgrund ungerechtfertigtem Aufwand.
