### ISSUE TITLE
SmartBlock Kontakt: Inline-Toolbar

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#899]
**Design:**
https://www.figma.com/design/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?node-id=1312-1498

--

**ToDo's:**
- [x] Edit in aus Toolbar entfernen und via Inline-Toolbar als Modal umsetzen
- [x] Modal für Nutzer anpassen
- [ ] Hintergrundfarbe in Quickedit aktivieren

**Comment by LisaS13** [comment]
- [ ] Fehlende Errormessage, wenn die Anhänge zu groß sind
