### ISSUE TITLE
Schrift-Upload optimieren

### ISSUE THREAD

**Issue by LisaS13** [wirDesign-communication-AG/wirhub-app#969]
**ToDo's:**
- [x] Schrift-Upload im Backend von Smart-Blocks / UI Pattern nach Design in einen neuen Tab "Schriften" umziehen. Bitte vor "Theme". Merci!
- [x] Schrift-Upload überarbeiten: hochgeladen werden können nur noch .woff2-Dateien und es können font-weight (100-900, "100 1000"(=Flex Font)) und font-style (normal / italic) pro Datei eingestellt werden

- [x] Auswahl der Font bei entsprechenden Theme Variablen
- [x] Entfall der Font Auswahl auf Theme Ebene
