### ISSUE TITLE
SmartBlock Video: Optimierungen

### ISSUE THREAD

**Issue by lisaschreyer** [wirDesign-communication-AG/wirhub-app#983]
**Design**
https://www.figma.com/design/kpIVnqrNdJhZL1eAoEf2hm/Smart-Blocks?node-id=254-7035&t=S4DOmyVf1lodNw9A-1 
<br>
**ToDo's Design:**
- [x] Überschrift entfernen
- [x] Text ergänzen
- [x] Textfarbe einstellbar
- [x] Abstand-Funktion analog Spalten-Modul ergänzen 
- [x] Text-Funktionen der Inline-Toolbar angleichen an Bild-Modul 
- [x] Hinweis für "stumm" beim Loop-Tooltip ergänzen
- [x] Abstände zwischen Video, Text und Download anpassen/ergänzen

**ToDo's Programmierung:**
- [x] Überschrift entfernen
- [x] Text ergänzen
- [x] Textfarbe einstellbar (über Quickedit)
- [x] Abstand-Funktion analog Spalten-Modul ergänzen (analog Spalten-Block)
- [x] Text-Funktionen ergänzen (analog Bild-Block): Layout-Positionen, Layout Ratio, Vertikale Ausrichtung
- [x] Hinweis für "stumm" beim Loop-Tooltip ergänzen
- [x] Abstände zwischen Video, Text und Download anpassen/ergänzen
